=== mmammel/projects/java/xmlNamespaceApply/Kelly.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:selection="http://www.findly.com" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.findly.com" elementFormDefault="qualified">  
  <xs:complexType name="AdditionalDataType">
    <xs:sequence>
      <xs:element name="UserData" type="selection:UserDataType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
	
  <xs:complexType name="UserDataType">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="Name" type="xs:string" minOccurs="0"/>
      <xs:element name="Value" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="UserInfoType">
    <xs:sequence>
      <xs:element type="xs:string" name="eTicketID"/>
      <xs:element type="xs:string" name="ScoreID"/>
      <xs:element type="xs:string" name="ExternalID"/>
      <xs:element type="xs:string" name="FirstName"/>
      <xs:element type="xs:string" name="LastName"/>
      <xs:element type="xs:string" name="ID"/>
      <xs:element type="selection:AdditionalDataType" name="AdditionalData" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ScaleType">
    <xs:sequence>
      <xs:element type="xs:string" name="Name"/>
      <xs:element type="xs:string" name="Score"/>
    </xs:sequence>
  </xs:complexType> 

  <xs:complexType name="ItemType">
    <xs:sequence>
      <xs:element type="xs:string" name="Qnum"/>
      <xs:element type="xs:string" name="Qtime"/>
      <xs:element type="xs:string" name="Qnid"/>
      <xs:element type="xs:string" name="Name"/>
      <xs:element name="Final" type="xs:string"/>
      <xs:element name="Wrong"  type="xs:string"/>
      <xs:element name="Level"  type="xs:string"/>
      <xs:element name="Topic"  type="xs:string"/>
      <xs:element type="xs:string" name="Comments"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ScoreInfoType">
    <xs:sequence>
      <xs:element type="xs:string" name="ScoreType"/>
      <xs:element type="xs:string" name="ReportURL"/>
      <xs:element type="xs:string" name="NumMetrics"/>
      <xs:element type="selection:MetricType" name="Metric" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TestInfoType">
    <xs:sequence>
      <xs:element type="xs:string" name="TestID"/>
      <xs:element type="xs:string" name="TestName"/>
      <xs:element type="xs:string" name="Date"/>
      <xs:element type="xs:string" name="DateAsNumber"/>
      <xs:element type="xs:string" name="TimeStart"/>
      <xs:element type="xs:string" name="TimeElapsed"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="MetricValueType" mixed="true">
    <xs:choice>
      <xs:sequence>
        <xs:element type="xs:string" name="NumItems" minOccurs="0"/>
        <xs:element type="selection:ItemType" name="Item" maxOccurs="unbounded" minOccurs="0" />
      </xs:sequence>
      <xs:sequence>
        <xs:element type="xs:string" name="NumScales" minOccurs="0"/>
        <xs:element type="selection:ScaleType" name="Scale" maxOccurs="unbounded" minOccurs="0" />
      </xs:sequence>
      <xs:sequence>
        <xs:element type="xs:string" name="ScoreBeg" minOccurs="0"/>
        <xs:element type="xs:string" name="ScoreInt" minOccurs="0"/>
        <xs:element type="xs:string" name="ScoreAdv" minOccurs="0"/>
      </xs:sequence>
      <xs:sequence>
        <xs:element type="xs:string" name="Rating" minOccurs="0"/>
      </xs:sequence>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="MetricType">
    <xs:sequence>
      <xs:element name="MetricName" type="xs:string"/>
      <xs:element name="MetricDesc"  type="xs:string"/>
      <xs:element name="MetricValue" type="selection:MetricValueType" maxOccurs="unbounded" /> 
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="ScoreType">
    <xs:sequence>
      <xs:element type="selection:UserInfoType" name="UserInfo" />
      <xs:element type="selection:TestInfoType" name="TestInfo" />
      <xs:element type="selection:ScoreInfoType" name="ScoreInfo" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ScoresType">
    <xs:sequence>
      <xs:element type="xs:string" name="NumScores"/>
      <xs:element type="selection:ScoreType" name="Score" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="Scores" type="selection:ScoresType"/>
  
</xs:schema>

=== mmammel/projects/java/xmlNamespaceApply/KellyTyping.xml
<?xml version="1.0" encoding="UTF-8"?>
<Scores xmlns="http://www.findly.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.findly.com Kelly.xsd">
  <NumScores>1</NumScores>
  <Score>
    <UserInfo>
      <eTicketID>4133575171848687528</eTicketID>
      <ScoreID>15533376</ScoreID>
      <ExternalID>0</ExternalID>
      <FirstName>Megan</FirstName>
      <LastName>Smith</LastName>
      <ID>2137</ID>
      <AdditionalData>
        <UserData />
      </AdditionalData>
    </UserInfo>
    <TestInfo>
      <TestID>EN_TYPK1</TestID>
      <TestName>Typing Test (KS)</TestName>
      <Date>7/5/2012</Date>
      <DateAsNumber>20120705</DateAsNumber>
      <TimeStart>20:28:40</TimeStart>
      <TimeElapsed>300</TimeElapsed>
    </TestInfo>
    <ScoreInfo>
      <ScoreType>STANDARD</ScoreType>
      <ReportURL>https://webtest.skillcheck.com/onlinetesting/servlet/com.skillcheck.session_management.SK_Servlet?ID=KSUS-1234&amp;MODE=REPORTRETRIEVAL,scoreKey.15533376,html</ReportURL>
      <NumMetrics>6</NumMetrics>
      <Metric>
        <MetricName>Rating</MetricName>
        <MetricDesc>Rating</MetricDesc>
        <MetricValue>
          <Rating>Basic</Rating>
        </MetricValue>
      </Metric>
      <Metric>
        <MetricName>GrossWPM</MetricName>
        <MetricDesc>Gross speed (words per minute)</MetricDesc>
        <MetricValue>50</MetricValue>
      </Metric>
      <Metric>
        <MetricName>Errors</MetricName>
        <MetricDesc>Total number of errors</MetricDesc>
        <MetricValue>30</MetricValue>
      </Metric>
      <Metric>
        <MetricName>AdjErrors</MetricName>
        <MetricDesc>Errors adjusted for time</MetricDesc>
        <MetricValue>18</MetricValue>
      </Metric>
      <Metric>
        <MetricName>NetWPM</MetricName>
        <MetricDesc>Net speed (words per minute)</MetricDesc>
        <MetricValue>32</MetricValue>
      </Metric>
      <Metric>
        <MetricName>AccuracyRate</MetricName>
        <MetricDesc>Accuracy percentage rate over time</MetricDesc>
        <MetricValue>-3499</MetricValue>
      </Metric>
    </ScoreInfo>
  </Score>
</Scores>

=== mmammel/projects/java/xmlNamespaceApply/KellyDataEntry.xml
<?xml version="1.0" encoding="UTF-8"?>
<Scores xmlns="http://www.findly.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.findly.com Kelly.xsd">
  <NumScores>1</NumScores>
  <Score>
    <UserInfo>
      <eTicketID>4133575171848687528</eTicketID>
      <ScoreID>15532957</ScoreID>
      <ExternalID>0</ExternalID>
      <FirstName>Megan</FirstName>
      <LastName>Smith</LastName>
      <ID>2137</ID>
      <AdditionalData>
        <UserData />
      </AdditionalData>
    </UserInfo>
    <TestInfo>
      <TestID>EN_DATY4</TestID>
      <TestName>Data Entry Test - Alphanumeric (F)(KS)</TestName>
      <Date>7/5/2012</Date>
      <DateAsNumber>20120705</DateAsNumber>
      <TimeStart>19:02:41</TimeStart>
      <TimeElapsed>300</TimeElapsed>
    </TestInfo>
    <ScoreInfo>
      <ScoreType>STANDARD</ScoreType>
      <ReportURL>https://webtest.skillcheck.com/onlinetesting/servlet/com.skillcheck.session_management.SK_Servlet?ID=KSUS-1234&amp;MODE=REPORTRETRIEVAL,scoreKey.15532957,html</ReportURL>
      <NumMetrics>6</NumMetrics>
      <Metric>
        <MetricName>Rating</MetricName>
        <MetricDesc>Rating</MetricDesc>
        <MetricValue>
          <Rating>Intermediate</Rating>
        </MetricValue>
      </Metric>
      <Metric>
        <MetricName>GrossKPH</MetricName>
        <MetricDesc>Gross speed (keystrokes per hour)</MetricDesc>
        <MetricValue>7572</MetricValue>
      </Metric>
      <Metric>
        <MetricName>Errors</MetricName>
        <MetricDesc>Total number of errors</MetricDesc>
        <MetricValue>15</MetricValue>
      </Metric>
      <Metric>
        <MetricName>AdjErrors</MetricName>
        <MetricDesc>Errors adjusted for time</MetricDesc>
        <MetricValue>540</MetricValue>
      </Metric>
      <Metric>
        <MetricName>NetKPH</MetricName>
        <MetricDesc>Net speed (keystrokes per hour)</MetricDesc>
        <MetricValue>7032</MetricValue>
      </Metric>
      <Metric>
        <MetricName>AccuracyRate</MetricName>
        <MetricDesc>Accuracy percentage rate over time</MetricDesc>
        <MetricValue>88</MetricValue>
      </Metric>
    </ScoreInfo>
  </Score>
</Scores>

=== mmammel/projects/java/xmlNamespaceApply/KellyCallCenter.xml
<?xml version="1.0" encoding="UTF-8"?>
<Scores xmlns="http://www.findly.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.findly.com Kelly.xsd">
  <NumScores>1</NumScores>
  <Score>
    <UserInfo>
      <eTicketID>420674316650216617</eTicketID>
      <ScoreID>15948666</ScoreID>
      <ExternalID>0</ExternalID>
      <FirstName>Davis</FirstName>
      <LastName>Nez</LastName>
      <ID>10535078</ID>
      <AdditionalData>
        <UserData />
      </AdditionalData>
    </UserInfo>
    <TestInfo>
      <TestID>EN_FLCK2</TestID>
      <TestName>Call Center Sales Scenarios (F) (KS)</TestName>
      <Date>9/13/2012</Date>
      <DateAsNumber>20120913</DateAsNumber>
      <TimeStart>18:34:33</TimeStart>
      <TimeElapsed>933</TimeElapsed>
    </TestInfo>
    <ScoreInfo>
      <ScoreType>CALLCENTER</ScoreType>
<ReportURL>https://webtest.skillcheck.com/onlinetesting/servlet/com.skillcheck.session_management.SK_Servlet?ID=KSUS-1234&amp;MODE=REPORTRETRIEVAL,scoreKey.15948666,html</ReportURL>
      <NumMetrics>2</NumMetrics>
      <Metric>
        <MetricName>OverallScore</MetricName>
        <MetricDesc>Overall score (not a percentage)</MetricDesc>
        <MetricValue>2.5</MetricValue>
      </Metric>
      <Metric>
        <MetricName>ScaleScores</MetricName>
        <MetricDesc>Scale names and scores</MetricDesc>
        <MetricValue>
          <NumScales>4</NumScales>
          <Scale>
            <Name>PROSPECTING</Name>
            <Score>3.0</Score>
          </Scale>
          <Scale>
            <Name>INFORMATION GATHERING/CONTROLLING THE SALE</Name>
            <Score>3.0</Score>
          </Scale>
          <Scale>
            <Name>OBJECTIONS</Name>
            <Score>2.5</Score>
          </Scale>
          <Scale>
            <Name>CLOSING</Name>
            <Score>2.0</Score>
          </Scale>
        </MetricValue>
      </Metric>
    </ScoreInfo>
  </Score>
</Scores>
